name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Configure Core RDP Settings
        run: |
          # Enable Remote Desktop and disable Network Level Authentication (If needed)
          Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "SecurityLayer" -Value 0 -Force
          
          # Remove any existing rule with the same name to avoid duplication
          netsh advfirewall firewall delete rule name="RDP-Tclallocate"
          

          # For testing, allow any incoming connection on port 3389
          netsh advfirewall firewall add rule name="RDP-Tclallocate" dir=in action=allow protocol=TCP localport=3389
          Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "fDenyTSConnections" -Value 0 -Force
Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "UserAuthentication" -Value 0 -Force
Set-ItemProperty -Path HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\ -Name "SecurityLayer" -Value 0 -Force

# Remove any existing rule with the same name to avoid duplication
netsh advfirewall firewall delete rule name="RDP-Tclallocate"

# For testing, allow any incoming connection on port 3389
netsh advfirewall firewall add rule name="RDP-Tclallocate" dir=in action=allow protocol=TCP localport=3389

# (Optional) Restart the Remote Desktop service to ensure changes take effect
Restart-Service -Name TermService -Force

- name: Create RDP User with Secure Password
  run: |
    Add-Type -AssemblyName System.Security
    $charSet = @(
        [char[]]([int][char]'A'..[int][char]'Z') # Upper (char[65].. 90) # A-Z
        [char[]]([int][char]'a'..[int][char]'z') # Lower (char[97]..122) # a-z
        [char[]]([int][char]'0'..[int][char]'9') # Number (char[48].. 57) # 0-9
        [char[]]([int][char]'!'..[int][char]('/') + [int][char](':'..[int][char]'@') + [int][char]('['..[int][char]'`') + [int][char]('{'..[int][char]'~')) # Special (char[33]..47) + (char[58]..64) + (char[91]..96) + (char[123]..126) # Special characters
    )

    $rawPassword = (
